networks:
  laravel:
    name: laravel
services:
  
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - ./src:/var/www/html
    ports:
      - 8001:80
      - 443:443
    networks:
      - laravel
  php:
    image: php:8.4-rc-fpm-alpine
    container_name: php
    networks:
      - laravel

  mysql:
    image: mysql:9.1.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - 3306:3306
    networks:
      - laravel
