networks:
  laravel:
    name: laravel
services:
  
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - php
      - mysql
    volumes:
      - ./src:/var/www/html
    ports:
      - 8001:80
      - 443:443
    networks:
      - laravel

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: php
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  
  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  artisan:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php","artisan"]
    networks:
      - laravel

  npm:
    image: node:21-alpine
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["npm"]
    networks:
      - laravel
